#
# Run workflow will run for every Pull Request and will need
# to be green on all bots before code can be merged.
#
# name: Pull Request
# on:
#   pull_request:
#     branches:
#       - dev
#     types:
#       - opened
#       - reopened
#       - synchronize
#       - ready_for_review

# jobs:
#   PR:
#     uses: Piracanjuba-FlutterFlow/arquivos-de-workflow-flutter/.github/workflows/pr.yml@dev
